name: build_jar.yml
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn install:install-file -Dfile=lib/bluej/extensions2/5.0.0/extensions2-5.0.0.jar -DgroupId=bluej -DartifactId=extensions2  -Dversion=5.0.0 -Dpackaging=jar -DgeneratePom=true
          mvn --batch-mode --update-snapshots clean
          mvn --batch-mode --update-snapshots package

      - name: Create staging directory
        run: mkdir -p staging && cp target/*.jar staging

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging