name: Build Installer

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  advinst-aip-build-demo:
    runs-on: windows-latest
    name: Build Aip Demo
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: 'false'
          submodules: 'false'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Download jcef-bundle
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'jcefmaven/jcefbuild'
          version: 'tags/1.0.53'
          file: windows-amd64.tar.gz
          target: jcef-bundle.tar.gz
          token: ${{ secrets.PAT_TOKEN }}

      - name: Unpack jcef-bundle
        run: |
          tar -xvzf jcef-bundle.tar.gz
          robocopy .\bin\lib\win64 .\jcef-bundle /E
          dir
          exit 0

      - name: Download B2J
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'ValentinHerrmann/Blockly2Java'
          version: 'latest'
          file: Blockly2Java.tar.gz
          target: Blockly2Java.tar.gz
          token: ${{ secrets.PAT_TOKEN }}

      - name: Unpack B2J
        run: |
          tar -xvzf Blockly2Java.tar.gz -C resources/Blockly
          cd resources/Blockly
          dir

      - name: Download Gameboard
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'ValentinHerrmann/Gameboard'
          version: 'latest'
          file: GameboardVorlage.jar
          target: GameboardVorlage.jar
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: List files
        run: |
          dir

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots clean 
          mvn --batch-mode --update-snapshots package -DskipTests 
      - name: Build AIP
        uses: caphyon/advinst-github-action@v2.0
        with:
          advinst-version: '22.4'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\extensions2\BBE.aip
          aip-build-name: DefaultBuild
          aip-package-name: BBE_Installer_${{ github.ref_name }}.msi
          aip-output-dir:  ${{ github.workspace }}\setup
          aip-commands: |
            SetProperty FOO="foo"
            SetVersion 1.2.0
            
      - name: Publish setup artifact
        uses: actions/upload-artifact@v4
        with:
          name: BBE_Installer_${{ github.ref_name }}
          path: ${{ github.workspace }}\setup\BBE_Installer_${{ github.ref_name }}.msi
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
            files: |
                ${{ github.workspace }}\setup\BBE_Installer_${{ github.ref_name }}.msi
            token: ${{ secrets.GH_TOK }}
