name: Build Advanced Installer Project (.AIP)  Demo
on: [workflow_dispatch]
jobs:
  advinst-aip-build-demo:
    runs-on: windows-latest
    name: Build Aip Demo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build AIP
        uses: caphyon/advinst-github-action@v2.0
        with:
          advinst-version: '21.7.1'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\extensions2\BBE.aip
          aip-build-name: DefaultBuild
          aip-package-name: blueJBlocklyInstaller.msi
          aip-output-dir:  ${{ github.workspace }}\setup
          aip-commands: |
            SetProperty FOO="foo"
            SetVersion 1.2.0
      - name: Publish setup artifact
        uses: actions/upload-artifact@v4
        with:
          name: setup
          path: ${{ github.workspace }}\setup\blueJBlocklyInstaller.msi
