name: Download Built Artifact
run-name: ${{ github.actor }} is testing out Download Artifact 🚀
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - id: download-release-asset
        name: Download release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'jcefmaven/jcefbuild'
          version: 'tags/1.0.53'
          file: windows-amd64.tar.gz
          target: jcef-bundle.tar.gz
          token: ${{ secrets.PAT_TOKEN }}
      - name: List files
        run: |
          ls -l
          tar -xvzf jcef-bundle.tar.gz
          ls -l
      
